-- Champs qualitatifs extraits par NLP pour fiabiliser l'estimation
ALTER TABLE biens ADD COLUMN IF NOT EXISTS parking_type VARCHAR(20);
ALTER TABLE biens ADD COLUMN IF NOT EXISTS has_piscine BOOLEAN;
ALTER TABLE biens ADD COLUMN IF NOT EXISTS exposition VARCHAR(10);
ALTER TABLE biens ADD COLUMN IF NOT EXISTS vue VARCHAR(20);
ALTER TABLE biens ADD COLUMN IF NOT EXISTS etat_interieur VARCHAR(20);
ALTER TABLE biens ADD COLUMN IF NOT EXISTS jardin_etat VARCHAR(20);
ALTER TABLE biens ADD COLUMN IF NOT EXISTS has_cave BOOLEAN;
ALTER TABLE biens ADD COLUMN IF NOT EXISTS has_gardien BOOLEAN;
ALTER TABLE biens ADD COLUMN IF NOT EXISTS has_double_vitrage BOOLEAN;
ALTER TABLE biens ADD COLUMN IF NOT EXISTS has_cuisine_equipee BOOLEAN;
ALTER TABLE biens ADD COLUMN IF NOT EXISTS is_plain_pied BOOLEAN;
ALTER TABLE biens ADD COLUMN IF NOT EXISTS standing_immeuble SMALLINT;
